 name: CI/CD workflow for Maven Build and Sonar Code scan


 name: My First GitHub Actions
 
on: [push]
 
jobs:

  build:

    runs-on: self-hosted
 
 
    steps:

    - uses: actions/checkout@v3

    - name: Set up Python

      uses: actions/setup-python@v2

      with:

        python-version: ${{ matrix.python-version }}
 
    - name: Install dependencies

      run: |

        python -m pip install --upgrade pip

        pip install pytest
 
        
 
    - name: Run tests

      run: |

        cd src

        python -m pytest addition.py
 
    - name: SonarQube Scan

      uses: sonarsource/sonarqube-scan-action@master

      with:

        projectBaseDir: .

        args: >

          -Dsonar.organization=my-org

          -Dsonar.projectKey=my-Java-web-app

      env:

        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}     
 
