name: "sonar_cloud_scan_github_actions"
on:
  workflow_dispatch:
 
jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Run tests with coverage
        run: |
          pytest --cov=. tests/
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=swathisony239
              -Dsonar.projectKey=SonarCloudCodeAnalyisis
              -Dsonar.sources=.
              -Dsonar.language=py
              -Dsonar.host.url=https://sonarcloud.io
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
              -Dsonar.python.coverage.reportPaths=coverage.xml
